### ISSUE TITLE
Fix Dynamic Honey Badger messaging logic.

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#122]
This is currently a bit fuzzy, vulnerable to replaying votes, and doesn't always guarantee that votes eventually get committed. Also, if the joining node only joins after the epoch where the vote for adding it reaches a majority, it won't know the exact vote count and won't be able to detect if it loses majority again.
A solution could look as follows.

We clear the vote counts, restart Honey Badger and set `start_epoch` to the current epoch every time one of the following conditions occurs:
* A change reaches majority: That change remains the "current" one until another change gets a majority of votes that are committed _after_ this epoch. Votes committed in older epochs are dismissed.
* Key generation for the current change completes.

Every key generation message (`Accept` or `Prepare`) is annotated with that `start_epoch` (that's already the case). Also, every change vote message is annotated with the `start_epoch` and in addition with an incrementing `vote_num`ber: That way, nodes can change their votes and old votes can't be replayed. For each validator, the vote that counts (if any) is the vote with the highest `vote_num` that has been committed in an epoch `>= start_epoch`.

For a vote, the message flow is:
* The validator that wants to cast the votes signs the desired change (`Add` or `Remove`) with the `start_epoch` and incremented `vote_num` and sends it to all the other validators.
* When we receive a vote, we put it into `pending_votes: BTreeMap<NodeUid, Vote>` _if_ it has the current `start_epoch`, and has a greater `vote_num` that the existing entry by the same signatory (or if there's no entry yet).
* In each new epoch, we propose all `pending_votes` that are not in `votes` yet.
* After each epoch's output, we put all committed votes into `votes`  _if_ they have the current `start_epoch` and they have a grater `vote_num` than the existing entry by the same signatory (if any). If there is a majority in `votes`, we set `current_change` to that vote, restart Honey Badger and clear `votes` and `pending_votes`. Key generation starts for the new change.

One drawback still remains: the joining node can't verify that it has won the vote and is about to be added. That can't hurt the network, but it's probably still important for the new node to _know_ whether it is actually expected. Also, it should know the current `start_epoch` so that it knows that it has received all votes, and that it will realize if another change gets a majority.
* We could leave it as is: Then it's the user's responsibility to get that information to the new node and verify it.
* We could add the `current_change` and `start_epoch` to each proposal. That is a bit wasteful, but then the new node would automatically receive it.
* We could add an additional `Restart(start_epoch, current_change)` message type, probably for new observers in general. Every time Honey Badger is restarted, that is sent to `Target::All`. The new node needs _f + 1_ `Restart` messages to trust them.

**Comment by c0gent** [comment]
I noticed this too. I'll form an opinion about what to do about this as I start plugging things into Parity and hopefully offer some useful suggestions.

**Comment by vkomenda** [comment]
> We could add an additional Restart(start_epoch, current_change) message type, probably for new observers in general. Every time Honey Badger is restarted, that is sent to Target::All. The new node needs f + 1 Restart messages to trust them.

Good point. If we need to carry over some state through node reset to other nodes - including any new nodes that might join - that could be done using a "bye" broadcast message which contains that useful state. Similarly to `Term` messages in `Agreement`.
