### ISSUE TITLE
Use stable for building on CI

### ISSUE THREAD

**Issue by mbr** [poanetwork/hbbft#128]
Disregarding Clippy & friends, should hbbft not start targeting stable instead of a specific nightly? I believe the CI can be made to work with both without great effort, I will gladly tackle the issue if someone agrees that this is a good idea.

**Comment by afck** [comment]
Yes, I think CI should at least build (and maybe test) on stable, and _also_ run rustfmt and Clippy on a specific nightly.

**Comment by afck** [comment]
This is complete, I think? (https://github.com/poanetwork/hbbft/pull/133)
