### ISSUE TITLE
`rand::Rand` is deprecated -- update `rand` version and Convert to `distributions::Standard`

### ISSUE THREAD

**Issue by c0gent** [poanetwork/hbbft#145]
TODO

**Comment by afck** [comment]
The only obstacle with that is that [pairing](https://github.com/zkcrypto/pairing) still uses rand 0.4, so I guess

```rust
let x: Fq = rand::random();
```

wouldn't work anymore?

**Comment by c0gent** [comment]
I see. Ok well we might have to update it there too.

**Comment by c0gent** [comment]
Well I've updated most of my crates that use rand to 0.5. It's mostly a find and replace but we'll have to see. Not a high priority.

**Comment by afck** [comment]
We're using rand 0.6.5 now. Closing this.
