### ISSUE TITLE
What should `QueueingHoneyBadger` do with a single validator?

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#147]
Currently `QueueingHoneyBadger` always immediately initiates the next epoch as soon as the previous one is output. That doesn't work for a single validator, since it always outputs immediately in every epoch, so it would just output empty batches in an infinite loop. We need to decide on the semantics here:

1. Don't allow single-validator networks. Refuse to construct an instance with a single validator, and terminate if one of two nodes leaves the network.
  _That makes it a bit cumbersome to start up a network. Starting with a single validator and adding more step-by-step would be convenient._

2. Make the user explicitly start the next epoch. Then they can determine a minimal batch time, and delay the epoch, or wait for another node or a transaction.
  _It might feel a bit unnatural if you explicitly have to trigger that every time. Also, it makes it easy to make the same mistake and just always trigger after output → infinite loop with a single validator._

3. Automatically start the new epoch, but only if there are either transactions in the queue or key generation messages pending.
  _That would block a network, though, if e.g. half the nodes have plenty of pending transactions and half of them don't have any._

4. Only automatically start the next epoch if there are either transactions in the queue, or key generation messages pending, or at least _k_ proposals from other nodes… for _k = f + 1_? Or _k = 1_?
  _That would still block if only k - 1 nodes have pending transactions. And if k ≤ f, it would allow an adversary to generate lots of empty blocks. But maybe that's not too bad? And k could be a configuration option._

**Comment by c0gent** [comment]
This is a tough one but I suspect something like option 4 would be best. 

Or how about check before incrementing the epoch that the network contains at least 2 (or x) nodes? If that won't work for some reason, I'd lean towards something like checking for at least k = f + 1 proposals.

**Comment by afck** [comment]
> Or how about check before incrementing the epoch that the network contains at least 2 (or x) nodes?

I just think it is unintuitive to apply different rules depending on _N_, especially in a setting where _N_ changes dynamically.
And option 4 would still have kind of similar effects: If you're the only validator, it means you start your epochs manually. If there are up to three validators, it means any one of them can start the next epoch (but if nobody does, no epoch is produced), and with four validators, the network waits for at least two validators' input, etc.
So I think I also tend towards option 4.
