### ISSUE TITLE
Move the crypto module into its own crate

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/hbbft#164]
The crypto module
* has a different commit dynamic to the rest of the `hbbft` crate,
* is related to the main code through an interface,
* has it's own CI tests that add up to the CI tests of `hbbft` and don't have to be run on every commit to the rest of `hbbft`.

Separating it into its own crate can also facilitate the research on other types of cryptography (#54) in `hbbft` because other crates could be designed to use the same interface.

Crypto-related issues such as #89 would move with the module as well.

**Comment by c0gent** [comment]
Yes it's a perfect candidate to be separated then. Sounds like it's probably a good idea to move it sooner rather than later.
