### ISSUE TITLE
Start a release cycle

### ISSUE THREAD

**Issue by c0gent** [poanetwork/hbbft#190]
Now that certain components, such as `threshold_crypto` are being moved into separate crates, I strongly suggest we start making regular crates.io releases to keep things coordinated. It will become a headache dealing with changes otherwise. I'm sure you guys have already discussed or thought about this (did we discuss this recently?) I just figured I'd create an issue for it.

Unfortunately, of course, this means we may also need to create our own semi-permanent fork of `merkle` (as I think Andreas may have mentioned to me recently) and possibly `reed-solomon-erasure` (and `pairing`?) for windows-msvc compatibility. If so we can just publish them as `hbbft-merkle`, etc. as is customary.

**Comment by c0gent** [comment]
Just so no one takes our names, I have created placeholder crates on `crates.io` for [`hbbft`](https://crates.io/crates/hbbft) and [`threshold_crypto`](https://crates.io/crates/threshold_crypto). @igorbarinov: Please create an 'igorbarinov' (it will match your github username) account on crates.io and I will transfer ownership of both placeholder crates to you. You can then remove me as an owner, or leave me if you want me to take care of the crates.io publishing (since I'm guessing I might have the most experience doing it -- not that it's the least bit difficult).

**Comment by afck** [comment]
With `merkle` replaced by our own implementation, only two remain: What are the issues with `reed-solomon-erasure` and `pairing`?
* For the former, we currently have a wrapper that makes it work in the trivial cases (no parity shards), but that wrapper is in `hbbft` itself. Is there an issue with Windows compatibility?
* For the latter, my pending PRs are not a requirement: `hbbft` uses the regular published version and contains its own wrappers for serialization.

So unless I'm missing something there should be nothing blocking a release on crates.io.

**Comment by afck** [comment]
([Done](https://crates.io/crates/hbbft))
