### ISSUE TITLE
Reliable broadcast by all of the participating nodes is not supported.

### ISSUE THREAD

**Issue by anthdm** [poanetwork/hbbft#20]
### Problem
The research paper describes that each in new `epoch` of `ACS` all participating nodes will propose their value in the RBC. If I take a look at the current implementation of the Reliable broadcast, I noticed that there is no support for that.

Is this correct? Have I miss interpreted the paper? Or did I miss something in the codebase?

**Comment by vkomenda** [comment]
Please have a look at
https://github.com/poanetwork/hbbft/blob/3d977c857505b183cf1b6340097080019b6595ae/src/honey_badger.rs#L121
There is the new top level of the algorithm implementing epochs.

**Comment by anthdm** [comment]
@vkomenda Thank you for pointing this out. I also looked at the common subset which indeed has multiple instances of `Broadcast`.
