### ISSUE TITLE
Travis fails with SIGILL. Clearing the cache fixes it.

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#201]
The CI tests on Travis sometimes fail with "`signal: 4, SIGILL: illegal instruction`" until we clear the Travis cache. I can't reproduce it locally.

**Comment by mbr** [comment]
#207, if merged, should give us some insight at least.

**Comment by afck** [comment]
We haven't seen this issue in a while. Please reopen if it happens again.
