### ISSUE TITLE
Test that the reordering attack on `BinaryAgreement` no longer succeeds

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/hbbft#228]
The reordering attack described in https://github.com/amiller/HoneyBadgerBFT/issues/59#issue-310368284 was avoided by adding `Conf` messages in #44, see also #37. We need a test that replays the attack and verifies that the attack does not succeed.

Closes #37.
Closes #45.

**Comment by d33a94975ba60d59** [comment]
I'll take this issue.
