### ISSUE TITLE
Change the license to MIT/Apache-2.0 by popular vote 

### ISSUE THREAD

**Issue by andogro** [poanetwork/hbbft#251]
The provisional GNU GPL license is too strong for this library and should be replaced with MIT/Apache-2.0.

To communicate approval, all project contributors (@afck, @vkomenda, @DrPeterVanNostrand, @mbr, @c0gent, @DemiMarie, @andogro, @igorbarinov, @ErichDonGubler) should reply in this thread with "I approve the license change to MIT/Apache-2.0"

**Comment by andogro** [comment]
I approve the license change to MIT/Apache-2.0

**Comment by ErichDonGubler** [comment]
Always in favor of things like this! I approve the license change to MIT/Apache-2.0.

**Comment by c0gent** [comment]
I approve the license change to MIT/Apache-2.0

**Comment by afck** [comment]
I approve the license change to MIT/Apache-2.0

**Comment by c0gent** [comment]
@yrashk, @natlg, @DemiMarie, @igorbarinov, please sign as described above. Thanks :)

**Comment by vkomenda** [comment]
I approve the license change to MIT/Apache-2.0

**Comment by DemiMarie** [comment]
I approve the license change to MIT/Apache-2.0

**Comment by igorbarinov** [comment]
I approve the license change to MIT/Apache-2.0

**Comment by mbr** [comment]
I approve the license change to MIT/Apache-2.0

**Comment by igorbarinov** [comment]
@DrPeterVanNostrand 👍 or 👎 for MIT/Apache-2.0 ?

**Comment by DrPeterVanNostrand** [comment]
I approve the license change to MIT/Apache-2.0

**Comment by natlg** [comment]
I approve the license change to MIT/Apache-2.0
