### ISSUE TITLE
Consider passing RNGs to the functions that use it, instead of boxing and storing them.

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#258]
It is more idiomatic to have e.g.:

```rust
fn handle_input<R: Rng>(&mut self, input: Self::Input, rng: &mut R);
```

instead of:

```rust
fn handle_input(&mut self, input: Self::Input);
```

We should figure out whether `&mut R` is really preferable to `R`, since `&mut R: Rng` if `R: Rng`, and whether there are any downsides to this approach in general.

**Comment by c0gent** [comment]
`RngCore` (the underlying trait) is [impl'd for `&mut RngCore`](https://docs.rs/rand_core/0.2.1/src/rand_core/lib.rs.html#343-363) so the additional indirection is unnecessary. In other words `R`, rather than `&mut R`) is the correct way to declare this (though it doesn't actually matter in practice).

**Comment by c0gent** [comment]
The same thing applies to rand 0.4 (before `RngCore` was a added) as well.

**Comment by afck** [comment]
I just find it weird that the rand crate itself doesn't follow that: E.g. [seq::sample_slice](https://docs.rs/rand/0.5.5/rand/seq/fn.sample_slice.html) and [Distribution::sample](https://docs.rs/rand/0.5.5/rand/distributions/trait.Distribution.html#tymethod.sample) take a `&mut R`—even though they explicitly make `R: ?Sized`. :thinking: 
But I agree, I don't see a reason for not just using `R`. (Maybe as a hint: "This doesn't need to consume your RNG."; but that's a bad reason, I think.)

**Comment by c0gent** [comment]
It's pretty common to have traits like this that take a type or a reference to a type. The only reason not to use `&mut R` in the definition is that it adds an unnecessary restriction. There's no reason that a user couldn't just pass the owned rng if they felt like it. It could make the usage a bit simpler on their in, for example if they were just passing a newly created rng every time for whatever reason and they didn't want to bother creating a binding for it and then passing `&mut myrng` etc.

**Comment by afck** [comment]
Done in https://github.com/poanetwork/hbbft/pull/357.
