### ISSUE TITLE
[Question] Can HBBFT achieve consensus on a fragmentary network?

### ISSUE THREAD

**Issue by diyism** [poanetwork/hbbft#284]
```
For example, I'm using wireguard to form a private network:
A(my home PC) connected to B(VPS), 
while B(VPS) connected to C(my office PC), 
but A and C won't connect each other directly, 
they are both behind NAT that wireguard can't traverse.
Their's VPN IPs are A(10.1.0.5), B(10.1.0.1), C(10.1.0.3).

If i run commands:
on A:   ./consensus-node --bind-address=10.1.0.5:9431 --remote-address=10.1.0.1:9431 --value=hello
on B:./consensus-node --bind-address=10.1.0.1:9431 --remote-address=10.1.0.5:9431
Then A and B responsed:
Broadcast succeeded! Node 0 output: hello
Broadcast succeeded! Node 1 output: hello

If i run commands:
on C: ./consensus-node --bind-address=10.1.0.3:9431 --remote-address=10.1.0.1:9431 --value=hello
on B: ./consensus-node --bind-address=10.1.0.1:9431 --remote-address=10.1.0.3:9431
Then C and B responsed:
Broadcast succeeded! Node 0 output: hello
Broadcast succeeded! Node 1 output: hello

But if i run commands:
on A:   ./consensus-node --bind-address=10.1.0.5:9431 --remote-address=10.1.0.1:9431 --remote-address=10.1.0.3:9431 --value=hello
on B:./consensus-node --bind-address=10.1.0.1:9431 --remote-address=10.1.0.5:9431 --remote-address=10.1.0.3:9431
On C:  ./consensus-node --bind-address=10.1.0.3:9431 --remote-address=10.1.0.1:9431 --remote-address=10.1.0.5:9431
Then they won't achieve consensus until timeout.

Can HBBFT achieve consensus on my fragmentary network?
```

**Comment by diyism** [comment]
Great, i'll give a try to hydrabadger tomorrow, thanks

**Comment by afck** [comment]
> Can HBBFT achieve consensus on my fragmentary network?

Not in general: From hbbft's perspective, it's the user's responsibility to ensure that every message sent from a correct node to a correct node eventually reaches its destination. In your example that would mean that in a real-world application, something like relay nodes need to be implemented, to get messages from A to C and from C to A.

However, hbbft tolerates any number of faulty nodes up to and excluding ⅓ of the network. So if among four nodes A, B, C and D, two cannot connect (e.g. A and C), it will still work (even without a relay mechanism). You can consider C "faulty" and the correct nodes will still be more than ⅔ of the network.

Please reopen if you have further questions.

**Comment by c0gent** [comment]
@diyism please feel free to create a new issue here or on the [Hydrabadger repo](https://github.com/poanetwork/hydrabadger) if you run into any problems or just to let us know how it went.  I'm happy to help or just to discuss.

**Comment by diyism** [comment]
> @diyism , you are trying to use a very old example. It doesn't run full consensus, only reliable broadrast. You might want to try an actively developed frontend https://github.com/poanetwork/hydrabadger. You should achieve consensus on a fragmented network.

@vkomenda, hydrabadger won't work, i've post detail over there: https://github.com/poanetwork/hydrabadger/issues/5

**Comment by afck** [comment]
Yes, I don't think Hydrabadger already implements any workaround for failling connections. Three nodes with one missing connection currently doesn't work.

**Comment by afck** [comment]
Sorry, "consensus-node" is just a very basic example to illustrate how to use the API. We don't have plans to extend it, or to support any failing connection there at all.

If we implement some kind of relay mechanism to work around connection problems, Hydrabadger would probably be the right place for it.

**Comment by vkomenda** [comment]
@diyism, thanks for the link. However it would be more relevant to a networking layer such as Hydrabadger, cc: @c0gent. The HBBFT repo contains the distributed algorithm only and will not address networking issues because the HoneyBadgerBFT algorithm assumes **eventual delivery of messages** which must be provided by a networking layer. For more details, see the HoneyBadgerBFT paper cited in the README.

Please correct me if I'm missing something about Mesh but the consistency model of HoneyBadgerBFT is stronger than that on gossip broadcast since the former ensures total order, Byzantine fault tolerance and censorship resilience in addition to consistency.

**Comment by VegeBun-csj** [comment]
@diyism hi, did you solved it ?
