### ISSUE TITLE
Consider making ThresholdDecryption work like ThresholdSign.

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#286]
`ThresholdSign` receives the to-be-signed data on construction. Its _input_ is `()`: It's only there to trigger sending the shares. This has the advantage that we can validate incoming signature shares even if `handle_input` wasn't called yet.

`ThresholdDecryption` receives the ciphertext via `handle_input`. This makes its implementation more complicated, but maybe it's more intuitive to use?

This feels inconsistent. We should decide on one approach. I'm leaning towards the former, depending on how much that complicates `ThresholdDecryption`'s use in `EpochState`.

**Comment by vkomenda** [comment]
In the latter approach, did you mean instead that `ThresholdSign` would receive a ciptertext through `handle_input`?

`ThresholdDecryption` currently already handles a ciphertext input.

**Comment by afck** [comment]
Yes, exactly: the second one is how `ThresholdDecryption` currently works; for `ThresholdSign` it would mean inputting the to-be-signed data in `handle_input` instead of the constructor.

**Comment by afck** [comment]
As @alyjak pointed out in https://github.com/poanetwork/hbbft/pull/312#discussion_r229513749, making TD work like TS would move quite a lot of complexity from (simple) TD to (already complex) `EpochState`.

It's probably a good thing that TD currently handles all cases automatically: decryption shares arriving before or after the ciphertext. So maybe it should be the other way round, and TS should do the same, i.e. not accept the data to sign in the constructor, but in the single `handle_input` call that triggers sending the share instead?

Another, even more flexible (but maybe unnecessarily complicated?) option would be to change both:
* No data/ciphertext in the constructor.
* One `set_data`/`set_ciphertext` call to set the data/ciphertext. (At this point, all previously received invalid shares can be discarded, and fault logs generated.)
* One separate `send_share` call to trigger sending our own share to the others.

…because in `EpochState`, we can't send the decryption share at the moment where we receive the ciphertext, and it would be convenient to store it directly in the `ThresholdDecryption` instance right away.

**Comment by afck** [comment]
Implemented in #316.
