### ISSUE TITLE
Question: Smart contracts, evm support, parity plugin

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/hbbft#331]
1. is there a community channel where I should ask those kind of questions?
2. Curious to understand how to use this powerful project with parity client and have evm support to run smart contracts.
3. What is transaction in current implementation? Is it account balance transfer? Is there any other types of transactions that currently supported.
4. Public key crypto. What kind of account types does it support? Can I use same eth based account structure?

Thank you

**Comment by vkomenda** [comment]
@rstormsf, I invited you to our gitter channel.

**Comment by afck** [comment]
Yes, Gitter or GitHub issues are both fine.

Regarding 2, 3 and 4: hbbft is a network-agnostic library that only implements the Honey Badger consensus mechanism itself. It doesn't have a notion of "account", "balance", "evm" or "smart contract", and the "transactions" it handles are completely generic, and have to be defined by a higher layer of the application.

Please have a look at [hydrabadger](https://github.com/poanetwork/hydrabadger) for a (work in progress) library that adds actual TCP networking to hbbft, and at our [ongoing Parity integration effort](https://github.com/poanetwork/parity-ethereum/tree/hbbft). The plan is to use hydrabadger inside a new `Hbbft` consensus engine inside Parity. Then it will support all the same kinds of accounts and smart contracts as Ethereum. (Possibly with added features like random numbers that don't depend on block hashes and aren't knowable in advance.)

Regarding cryptography: _Internally_, hbbft uses [threshold_crypto](https://github.com/poanetwork/threshold_crypto), but that will not affect the user. Accounts will use the same cryptography as in existing Ethereum-type networks.
