### ISSUE TITLE
How to join the network with an existing key share

### ISSUE THREAD

**Issue by sgeisler** [poanetwork/hbbft#365]
All the `join` logic of the `DynamicHoneyBadger` seems to assume that the joining party will need a new key share and that the other parties have to agree to let it join. But there is also the use case where you have a fixed set of validators that might go offline from time to time but basically just need to know the current epoch and era to join again.

Am I missing something or is it just not implemented (and would you accept a patch that implements it?)?

**Comment by vkomenda** [comment]
Sorry @sgeisler if I'm misunderstanding. This issue is probably to do with the networking layer more than with the algorithm itself. The offline validators remain to be peers in the sender queues of the validators which remain online. The validators keep track of each other's epochs by exchanging `EpochStarted` messages. In case when a validator goes offline between sending two such successive messages, other validators would keep on sending messages to the offline validator for the epoch in which it was last seen. You need to queue those messages at the networking layer. No rejoining is necessary. As soon as the offline validator comes back online, send it those queued messages and the sender queues will catch up by sending messages for epochs missed by the validator.

**Comment by sgeisler** [comment]
I agree that queuing is the right solution for short term outages since you have to provide reliable delivery anyway. But for longer outages I think it's better to just drop the connection, flush the queue and wait for the validator to come online again and let it rejoin. Let's consider the following example:

> Validator `0` has a hardware failure and needs to order a new server first. This can easily take a month. But since there are 30 validators anyway this is ok. But now everyone had to keep really big and even worse *persistent* queues (because validators `1..30` could reboot after each other and loose their non-persistent state). After coming online again `0` had to process all these messages at once which could take quite some time (and serves no real purpose since all decisions are made already anyway).

This shouldn't be something used to recover from dropped TCP connections but rather severe longer-lasting failures.

**Comment by sgeisler** [comment]
After thinking a little bit more about it I came to the conclusion that even if you don't have long outages but loose your state/memory (e.g. reboot) you need this functionality because messages with an epoch too far in the future will be [treated as a `Fault`](https://github.com/poanetwork/hbbft/blob/master/src/honey_badger/honey_badger.rs#L114) by us if we start from epoch 0 and limit the maximum future epochs (which we should to avoid DoS attacks).

**Comment by vkomenda** [comment]
> messages with an epoch too far in the future will be treated as a Fault

Are you considering DHB alone without the sender queue? The suggested use of `DynamicHoneyBadger` is within a `SenderQueue`, like in the tests. If you follow this, no node will ever receive a message too far in the future.

If you have a different queueing mechanism, please explain it.

**Comment by sgeisler** [comment]
Yes, I didn't know about the `SenderQueue` struct in your crate so far and played around with bare `QueuingHoneyBadger`s. 

But sending no messages or dropping them if they were sent prematurely doesn't really matter in the case I describe:

1. Every validator is working correctly till epoch `n`
2. Validator `F` crashes
3. After restarting validator `F` needs to construct a new `DynamicHoneyBadger` with an epoch larger or equal than the smallest epoch you have all messages for (`n+1`).

If you were to construct it with epoch 0 (which is the only possibility right now without a join plan) then you couldn't process the messages queued for you (no matter if you are using the `SenderQueue`).

As I said, I might be missing something here, but so far I heard no argument for how I could recover from a crash where I loose all my honey badger internal state (or how I could avoid loosing it, which I guess would make things much slower due to all the disk `sync`ing).

**Comment by afck** [comment]
That's true, so far our intention was to support only short-term connectivity losses (via `SenderQueue`), and for longer outages the application is expected to remove the lost node (involving a round of key generation) and then re-add it (another round of key generation).

But I think it would be feasible to add a mechanism to re-join with an existing key share after an outage, and I agree that we should. Not sure yet how complicated it would be:
* The crashed node must have saved at least its node ID, secret key and secret key share.
* The other nodes somehow need to tell it what the current era-epoch pair is. (Unfortunately `DynamicHoneyBadger` keeps a separate `era` number at the moment, and `HoneyBadger` restarts in `epoch` `0` whenever the set of validators changes. That is transparent to the user—they are added together—, but rejoining wouldn't work if you're at `8 + 0` and they're at `5 + 3`.)
* It also needs to have saved the full [`NetworkInfo`](https://github.com/poanetwork/hbbft/blob/1c7fc60db9a1b5562ccfcbc29155f4fda8d1530f/src/dynamic_honey_badger/dynamic_honey_badger.rs#L221)—or it also needs to learn all the node IDs, public keys and key shares from the other nodes.
* The other nodes need to make sure that the re-joined node receives all messages from the epoch where it returned.

Some of this will affect the `queueing_honey_badger` and `dynamic_honey_badger` modules, and some of it will actually happen on the application level, outside of hbbft. Any changes also need to be compatible with `sender_queue`.

Unfortunately in the short term our team is very busy, so it will take a while until we get around to this one. :sweat_smile: 
But contributions are welcome, and we're always happy to help, discuss and review!

**Comment by igorbarinov** [comment]
Hey @sgeisler 
I'm curious where do you plan to use the hbbft library?

**Comment by sgeisler** [comment]
@igorbarinov I'm currently looking into it's applicability for federated sidechains. Hbbft and BEAT seemed to be the best fit and when I found this project (rust, good code quality and documentation) I decided to build a prototype using it (that's what I'm doing now).

**Comment by afck** [comment]
Awesome!
We've looked into the BEAT paper, too; in the long term I hope we'll be able to add some of the improvements suggested there to hbbft.
