### ISSUE TITLE
HoneyBadgerBFT in a trustless system with frequent validator elections

### ISSUE THREAD

**Issue by ldmberman** [poanetwork/hbbft#380]
Hello,

I wonder if HoneyBadgerBFT can be useful in a trustless public system where new validators are elected frequently (like a PoS blockchain). The concerns arise due to the need to generate threshold encryption keys required by the Common Coin. The generation itself depends on the consensus on the order of the operations to perform. A partially synchronous system that does not require trustless setup (like pBFT) could be used to generate the keys, which can be then used in many subsequent consensus rounds. However, if the validator elections are frequent (and thus a timeout based consensus is needed every now and then to generate the keys), the purpose of an asynchronous consensus seems to be defeated.

Would greatly appreciate your thoughts on the matter.

**Comment by vkomenda** [comment]
Thanks for your question. We are interested to know what uses might community come up with for this consensus algorithm. Whether or not it is suitable for your concrete application very much depends on the type of _public system_ you are designing. It would work if at any point in time the set of validators is sufficiently small for HBBFT to have small enough latency. One possible solution that would work is to reuse the threshold signatures that are produced by the algorithm anyway as the source of distributed randomness that is applied by the PoS protocol to the set of potential validators to compute the next set of validators. There are two advantages: 1) the distributed randomness is free; 2) the transition to the next set of validators does not require a dedicated application of consensus as it is determined by the distributed randomness which is as secure and censorship-proof as threshold signatures are.

As you will notice in our code, we've [optimised](https://github.com/poanetwork/hbbft/blob/d4a7b19adb7021efcefdf735f6dd2c45cce0a1d2/src/binary_agreement/binary_agreement.rs#L438) the Binary Agreement algorithm and it no longer generates threshold signatures in every common coin epoch.

I don't think the purpose of asynchronous consensus is defeated by the need to regenerate keys frequently. [Trustless distributed key generation](https://github.com/poanetwork/hbbft/blob/d4a7b19adb7021efcefdf735f6dd2c45cce0a1d2/src/sync_key_gen.rs#L302) is a synchronous protocol that runs on top of _a_ consensus algorithm. In our case that algorithm is HBBFT but you may try it with pBFT if you wish. Key generation is at a higher level compared to HBBFT or pBFT. You implement the former using the latter, not the other way round. When you layer higher-level algorithms on top of an asynchronous consensus algorithm, they benefit from asynchronicity at the base level even if those higher-level algorithms are synchronous themselves.

Sorry if I misunderstood your concerns. Feel free to disagree or give more background information.

**Comment by afck** [comment]
Yes, that's exactly how we're planning to use it in the long term, and I think it's perfectly suited for that!

First of all, there are [_asynchronous_ algorithms for distributed key generation (DKG)](https://eprint.iacr.org/2012/377.pdf), and I think the [threshold_crypto crate](https://github.com/poanetwork/threshold_crypto) contains all the tools (bivariate polynomials and their commitments) to implement them. Our excuse for being too lazy to do so is that it's _much_ simpler to write a [synchronous one](https://github.com/poanetwork/hbbft/blob/master/src/sync_key_gen.rs) and if you already have a preexisting blockchain (which, if it uses hbbft, is actually based on a fully asynchronous algorithm), you can run the synchronous DKG on-chain:
What we mean by "synchronous" here is simply that `SyncKeyGen` must handle all messages in exactly the same order in all nodes. By putting the messages on the blockchain you can easily achieve that, even if the underlying network makes no synchronicity assumption.

We even implemented that in [`DynamicHoneyBadger`](https://github.com/poanetwork/hbbft/blob/master/src/dynamic_honey_badger/dynamic_honey_badger.rs), which wraps `HoneyBadger`, automatically performs DKG and thereby allows dynamically changing the set of validators on the fly. You can either use our implementation directly or use it as an example to guide you in how you use `HoneyBadger` (or even something lower-level, depending on how fine-grained control you need).

The only remaining problem with that is, of course, how to start a new network. Then there's no preexisting one to run DKG on. But I feel there's so many other options that it also doesn't warrant implementing an asynchronous DKG:
* You could start a network with a single validator, and run DKG on it. If that validator is faulty, just try again with another one, until you have a running network.
* You could start with a trusted dealer to bootstrap the network, then run DKG on it. After that, everyone has a safe key share.
* You could run a very simple "asynchronous" DKG that isn't fault-tolerant. Above, I lied about the requirements of our `SyncKeyGen` implementation: It doesn't actually need to handle the same messages in the same order. It just needs to make sure that when generating the keys, all nodes have handled enough `Ack` messages for the exact same set of `Part` messages. You can exchange all those messages and if after a minute one of the participants still hasn't contributed their messages, you just try again, without them. (Let me know if you'd like to try that approach; I'm happy to provide more details.)

Ah, great, now I've been ninja'd by @vkomenda! :laughing: 
Sending anyway. For redundancy and fault tolerance! :sunglasses: 

Good point about the number of validators: But I think if the set of elected validators is small enough (maybe 30, but probably more is also feasible) performance shouldn't be a problem.

**Comment by ldmberman** [comment]
Thank you for your input, guys, it is very helpful! Indeed, what I missed is that a new set of validators can perform a DKG by committing key shares in the current round still run by the old set of validators. I was worried about technics like "wait for a minute and repeat if messages have not arrived" cause byzantine actors can use them to break liveness, but when only used to kickstart the network they do seem reasonable, and a good alternative to using a different blockchain.

**Comment by afck** [comment]
Closing this. Please reopen if you have any further questions.
