### ISSUE TITLE
Add a HoneyBadger getter to DynamicHoneyBadger.

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#381]
It should be possible to get an immutable reference to the `HoneyBadger` contained in a `DynamicHoneyBadger`, so properties like `received_proposals` can be read.

**Comment by RicoGit** [comment]
Hi! `DynamicHoneyBadger` has field `honey_badget` with type `HoneyBadger<InternalContrib<C, N>, N>` where `InternalContrib` is private struct. It doesn't allow to create a getter for `honey_badger` filed without making `InternalContrib` public. Is it okay to make this struct public?

**Comment by vkomenda** [comment]
Sure. The fields of `InternalContrib` will remain private anyway.

**Comment by trendsetter37** [comment]
Should this issue be closed on account of [PR#383](https://github.com/poanetwork/hbbft/pull/383)?

**Comment by afck** [comment]
You're right, thanks!
