### ISSUE TITLE
Why isn't there an example telling how to use QueueingHoneyBadger with socket

### ISSUE THREAD

**Issue by LuminousXLB** [poanetwork/hbbft#407]
There are two examples now in the project.

`simulation` builds several QueueingHoneyBadger instances in a single process
`consensus-node` creates several processes but never uses the QueueingHoneyBadger struct

Why isn't there an example that several QHB instances communicate on socket?

**Comment by vkomenda** [comment]
@LuminousXLB, please check [Hydrabadger](https://github.com/poanetwork/hydrabadger). We deliberately avoided adding networking in `hbbft` to have a clean separation between the algorithm and the IO. The networking should be done at a different layer, and Hydrabadger provides an example of such a layer.

**Comment by LuminousXLB** [comment]
@vkomenda Thank you very much. I have been scratching on this for several weeks
