### ISSUE TITLE
Is there any solution to do some customized verification

### ISSUE THREAD

**Issue by LuminousXLB** [poanetwork/hbbft#412]
We want to verify the transaction proposed during the process of consensus. Is there anywhere that we can define customized logic for verification in `hbbft`?

Thanks

**Comment by vkomenda** [comment]
Can you clarify when you need transactions to be verified and by whom?

Transactions are input as `Input::User` and output in the `contributions` field of a `Batch`. So the time when you can verify transactions are before you input them or after `HoneyBadger` outputs them. In the latter case you would process the `Batch` in your application.

**Comment by LuminousXLB** [comment]
@vkomenda Thanks for your reply. I had thought that the verification should complete in the process of Binary Agreement. I'm going to do the verification before input it to `HoneBadger`.

Thanks
