### ISSUE TITLE
Add a method for skipping the current epoch.

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#413]
We could add a `*HoneyBadger::skip_epoch` method that would delete all information about the current epoch and move on to the next, without ever outputting the skipped epoch's batch.

This is dangerous, of course, and needs to be well-documented: It must only be called if the upper layer can guarantee that every instance that hasn't output the batch yet will call this method.

An example is the use in a blockchain: If our `HoneyBadger` instance is still working on block number 42, but we've just imported the complete, finalized block 42, we can probably be sure that every node will eventually import it and can call `skip_epoch`.

**Comment by dforsten** [comment]
That would be helpful, could we get it assigned and implemented within the next days?
It is the only issue I am currently aware of impairing the stability of the test net setup - I would like to demo it together with a Blockscout instance at an upcoming event.

**Comment by afck** [comment]
OK, I'll give it a try tomorrow.

**Comment by dforsten** [comment]
Great, thanks Andreas! :-)
