### ISSUE TITLE
Report faulty nodes.

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#51]
Keep a log of events that prove that a particular node is faulty, and propagate that information up, e.g. via a `DistAlgorithm::get_fault_log` method. (See #24.)

**Comment by vkomenda** [comment]
Errors can be logged at least in `HoneyBadger` in those places where there are TODOs to start logging something. So far there are 3 such TODOs:

1) an incorrect message from a known sender:
https://github.com/poanetwork/hbbft/blob/e0a85a54bbaf968107e4784ba2f8ca2c9e012fc4/src/honey_badger.rs#L238

2) an incorrect ciphertext computed for a known proposer node:
https://github.com/poanetwork/hbbft/blob/e0a85a54bbaf968107e4784ba2f8ca2c9e012fc4/src/honey_badger.rs#L412

3) decryption failure for a konwn proposer:
https://github.com/poanetwork/hbbft/blob/e0a85a54bbaf968107e4784ba2f8ca2c9e012fc4/src/honey_badger.rs#L435

each related to failures related to processing encrypted messages or ciphertexts. However the same logging improvement can be applied to other places possibly in other algorithms too where we, say, return `Ok(())` or simply `()` when some check fails, and the reason for that failure is likely to be some remote node that we can identify on the spot.

**Comment by afck** [comment]
(Note that the log shouldn't just be command line output; the user should be able to programmatically learn about malicious nodes and act on it.)
