### ISSUE TITLE
Reduce the memory footprint of a decryption share in HoneyBadger

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/hbbft#77]
PR #68 introduced a new kind of `HoneyBadger` message that contains a decryption share of the `CommonCoin` for the threshold encryption scheme. The decryption share contains a vector of 48 bytes which is the compressed representation of a group element. #68 took a rather relaxed view on optimization of memory usage and simply cloned the same share from local storage to a message. This can be optimised by wrapping the locally stored share into an `Rc` and cloning that `Rc` to the message instead of the whole vector. However, since serialization is not derivable for `Rc`, that required defining custom `Serialization` and `Deserialization` instances for `HoneyBadger::Message`, or possibly using an attribute `#[serde(with = "a_new_rc_serde_module")]`.

**Comment by afck** [comment]
Sorry, that was my fault! I somehow thought of the decryption share as containing a part of the transaction data (like the shares in Broadcast)!
Thanks for clearing that up! I'd say cloning 48 bytes is totally fine.
