### ISSUE TITLE
Make sure secret keys are always inside a `ClearOnDrop`.

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#89]
Overwriting the memory containing a secret key (#57) can still easily be forgotten: e.g. `SecretKey::new` returns a key outside of a `ClearOnDrop`.

Maybe the current `SecretKey` should be turned into a private `SecretKeyInner`, and put a `ClearOnDrop<Box<SecretKeyInner>>` inside the new `SecretKey`, so that outside of the `crypto` module there's no way to circumvent it anymore?

**Comment by DrPeterVanNostrand** [comment]
I don't think that the `secrets` crate takes the same precautions to circumvent the rustc optimization of eliding zeroing out secret data if that memory won't be used again; `clear_on_drop` takes special care in this regard.  However, `secrets` does add a few extra security features like making sure secret values are not included in core dumps and the addition of stack canaries.

Also, the dalek cryptography crate designers chose to use `clear_on_drop` over `secrets`, I'm not sure why exactly, I'll have to read up on it. [Here](https://github.com/dalek-cryptography/curve25519-dalek/issues/11) is an issue where the dalek authors discuss the problem of clearing secrets from memory.

As far a linking to libsodium, I don't know if that is a requirement that I'm willing to put on the user. Personally, I hate it when I'm trying to use a library in a language other than C, but first I have to build and link all of my dependencies. But Idk, what do you (@afck, @mbr) think?

**Comment by DrPeterVanNostrand** [comment]
> `unsafe { sodium::free(self.ptr) }`

After thinking about it, I don't think that the compiler is smart enough to elide a call to a C function. So elision of the memory clearing code may not be a problem with `secrets`.

**Comment by afck** [comment]
Yes, I imagine that won't be optimized away, but I agree that the sodium dependency is annoying. Maybe `secrets` could be modified to depend on one of the sodium Rust crates instead, that vendor the C library?

Anyway, I don't have a strong opinion regarding `clear_on_drop` vs. `secrets` in general.

**Comment by mbr** [comment]
I did not understand yet why we are not using an "established" crate that protects memory, I assume it was due to the libsodium dependency? Or was it just not generic enough? I would think that disabling swap is fairly important for keys.

There's also the tradeoff between implementing `Debug` and otherwise preventing accidental leakage. I did try to address this with another crate a while ago: https://github.com/49nord/sec-rs , it is probably more of a nice to have.

@DrPeterVanNostrand: If you think these are valid concerns, feel free to reopen the issue. Sorry!

**Comment by c0gent** [comment]
I agree Marc, At some point we should use something like https://github.com/quininer/seckey.

**Comment by DrPeterVanNostrand** [comment]
Reopening issue for lack of `mlock`. The solution should have the attributes:

- Must not result in a copy/move of a secret.
- The portion of memory where the secret is allocated must not be swapped to disk.
- The portion of memory where the secret is allocated must be cleared on drop.
- The clearing of data must be elision proof.
- Must be implemented for the `hbbft` types: `SecretKey`, `Poly`, `BivarPoly` (`Fr` and `Vec<Fr>`).
- Must not require the user to bring in non-Rust dependencies.
